OKTA_CLIENT_ID: "0oa1nuv3g2ori9Ibd5d7"

OKTA_CLIENT_SECRET: "iXlmhcUsBw5-Y2tAqG3LFfp428MczechzD2c3a7p"

OKTA_ORG: "dev-7460402"
OKTA_DOMAIN: "okta"

OKTA_URL: "https://dev-7460402.okta.com"

OKTA_ISSUER: "https://dev-7460402.okta.com/oauth2/default"

OKTA_AUTH_SERVER_ID: "default"

OKTA_REDIRECT_URI: "http://localhost:3000/users/auth/oktaoauth/callback"